package com.alteratom.dashboard.icon

import com.alteratom.R

object IconsAll {
    val lineIcons = listOf(
        Icon(R.drawable.il_arrow_align_center_h, "l", "arrow"),
        Icon(R.drawable.il_arrow_align_center_v, "l", "arrow"),
        Icon(R.drawable.il_arrow_angle_double_down, "l", "arrow"),
        Icon(R.drawable.il_arrow_angle_double_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_angle_double_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_angle_double_up, "l", "arrow"),
        Icon(R.drawable.il_arrow_angle_down, "l", "arrow"),
        Icon(R.drawable.il_arrow_angle_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_angle_left_b, "l", "arrow"),
        Icon(R.drawable.il_arrow_angle_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_angle_right_b, "l", "arrow"),
        Icon(R.drawable.il_arrow_angle_up, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_h, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_h_alt, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_left_down, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_maximize, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_merge, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_resize, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_resize_h, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_resize_v, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_right_down, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_shrink_h, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_shrink_v, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_up_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_v, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrows_v_alt, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_break, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_circle_down, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_circle_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_circle_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_circle_up, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_compress_h, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_down, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_down_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_down_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_from_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_from_top, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_growth, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_random, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_resize_diagonal, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_to_bottom, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_to_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_up, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_up_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_arrow_up_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_caret_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_chart_down, "l", "arrow"),
        Icon(R.drawable.il_arrow_compress_alt, "l", "arrow"),
        Icon(R.drawable.il_arrow_compress_alt_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_compress_arrows, "l", "arrow"),
        Icon(R.drawable.il_arrow_compress_point, "l", "arrow"),
        Icon(R.drawable.il_arrow_corner_down_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_corner_down_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_corner_down_right_alt, "l", "arrow"),
        Icon(R.drawable.il_arrow_corner_left_down, "l", "arrow"),
        Icon(R.drawable.il_arrow_corner_right_down, "l", "arrow"),
        Icon(R.drawable.il_arrow_corner_up_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_corner_up_left_alt, "l", "arrow"),
        Icon(R.drawable.il_arrow_corner_up_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_corner_up_right_alt, "l", "arrow"),
        Icon(R.drawable.il_arrow_direction, "l", "arrow"),
        Icon(R.drawable.il_arrow_download_alt, "l", "arrow"),
        Icon(R.drawable.il_arrow_enter, "l", "arrow"),
        Icon(R.drawable.il_arrow_exchange, "l", "arrow"),
        Icon(R.drawable.il_arrow_exchange_alt, "l", "arrow"),
        Icon(R.drawable.il_arrow_expand_alt, "l", "arrow"),
        Icon(R.drawable.il_arrow_expand_arrows, "l", "arrow"),
        Icon(R.drawable.il_arrow_expand_arrows_alt, "l", "arrow"),
        Icon(R.drawable.il_arrow_expand_from_corner, "l", "arrow"),
        Icon(R.drawable.il_arrow_expand_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_expand_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_export, "l", "arrow"),
        Icon(R.drawable.il_arrow_import, "l", "arrow"),
        Icon(R.drawable.il_arrow_left_arrow_from_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_left_arrow_to_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_maximize_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_scaling_left, "l", "arrow"),
        Icon(R.drawable.il_arrow_scaling_right, "l", "arrow"),
        Icon(R.drawable.il_arrow_scroll, "l", "arrow"),
        Icon(R.drawable.il_arrow_scroll_h, "l", "arrow"),
        Icon(R.drawable.il_arrow_shuffle, "l", "arrow"),
        Icon(R.drawable.il_arrow_sort, "l", "arrow"),
        Icon(R.drawable.il_arrow_sorting, "l", "arrow"),
        Icon(R.drawable.il_arrow_top_arrow_from_top, "l", "arrow"),
        Icon(R.drawable.il_arrow_top_arrow_to_top, "l", "arrow"),
        Icon(R.drawable.il_arrow_upload_alt, "l", "arrow"),
        Icon(R.drawable.il_business_analysis, "l", "business"),
        Icon(R.drawable.il_business_analytics, "l", "business"),
        Icon(R.drawable.il_business_bag, "l", "business"),
        Icon(R.drawable.il_business_bag_alt, "l", "business"),
        Icon(R.drawable.il_business_bill, "l", "business"),
        Icon(R.drawable.il_business_bitcoin_circle, "l", "business"),
        Icon(R.drawable.il_business_bitcoin_sign, "l", "business"),
        Icon(R.drawable.il_business_briefcase, "l", "business"),
        Icon(R.drawable.il_business_briefcase_alt, "l", "business"),
        Icon(R.drawable.il_business_calculator_alt, "l", "business"),
        Icon(R.drawable.il_business_calendar_alt, "l", "business"),
        Icon(R.drawable.il_business_chart, "l", "business"),
        Icon(R.drawable.il_business_chart_bar, "l", "business"),
        Icon(R.drawable.il_business_chart_bar_alt, "l", "business"),
        Icon(R.drawable.il_business_chart_growth, "l", "business"),
        Icon(R.drawable.il_business_chart_growth_alt, "l", "business"),
        Icon(R.drawable.il_business_chart_line, "l", "business"),
        Icon(R.drawable.il_business_chart_pie, "l", "business"),
        Icon(R.drawable.il_business_chart_pie_alt, "l", "business"),
        Icon(R.drawable.il_business_coins, "l", "business"),
        Icon(R.drawable.il_business_comparison, "l", "business"),
        Icon(R.drawable.il_business_credit_card, "l", "business"),
        Icon(R.drawable.il_business_crosshair, "l", "business"),
        Icon(R.drawable.il_business_crosshairs, "l", "business"),
        Icon(R.drawable.il_business_crosshair_alt, "l", "business"),
        Icon(R.drawable.il_business_dollar_alt, "l", "business"),
        Icon(R.drawable.il_business_dollar_sign, "l", "business"),
        Icon(R.drawable.il_business_dollar_sign_alt, "l", "business"),
        Icon(R.drawable.il_business_euro, "l", "business"),
        Icon(R.drawable.il_business_euro_circle, "l", "business"),
        Icon(R.drawable.il_business_gold, "l", "business"),
        Icon(R.drawable.il_business_graph_bar, "l", "business"),
        Icon(R.drawable.il_business_hunting, "l", "business"),
        Icon(R.drawable.il_business_invoice, "l", "business"),
        Icon(R.drawable.il_business_lightbulb, "l", "business"),
        Icon(R.drawable.il_business_lightbulb_alt, "l", "business"),
        Icon(R.drawable.il_business_lira_sign, "l", "business"),
        Icon(R.drawable.il_business_moneybag, "l", "business"),
        Icon(R.drawable.il_business_moneybag_alt, "l", "business"),
        Icon(R.drawable.il_business_money_bill, "l", "business"),
        Icon(R.drawable.il_business_money_bill_stack, "l", "business"),
        Icon(R.drawable.il_business_money_insert, "l", "business"),
        Icon(R.drawable.il_business_money_stack, "l", "business"),
        Icon(R.drawable.il_business_money_withdraw, "l", "business"),
        Icon(R.drawable.il_business_money_withdrawal, "l", "business"),
        Icon(R.drawable.il_business_panel_add, "l", "business"),
        Icon(R.drawable.il_business_percentage, "l", "business"),
        Icon(R.drawable.il_business_pound, "l", "business"),
        Icon(R.drawable.il_business_pound_circle, "l", "business"),
        Icon(R.drawable.il_business_presentation_line, "l", "business"),
        Icon(R.drawable.il_business_puzzle_piece, "l", "business"),
        Icon(R.drawable.il_business_receipt, "l", "business"),
        Icon(R.drawable.il_business_receipt_alt, "l", "business"),
        Icon(R.drawable.il_business_rupee_sign, "l", "business"),
        Icon(R.drawable.il_business_schedule, "l", "business"),
        Icon(R.drawable.il_business_signal_alt_3, "l", "business"),
        Icon(R.drawable.il_business_sitemap, "l", "business"),
        Icon(R.drawable.il_business_suitcase, "l", "business"),
        Icon(R.drawable.il_business_suitcase_alt, "l", "business"),
        Icon(R.drawable.il_business_university, "l", "business"),
        Icon(R.drawable.il_business_usd_circle, "l", "business"),
        Icon(R.drawable.il_business_usd_square, "l", "business"),
        Icon(R.drawable.il_business_yen, "l", "business"),
        Icon(R.drawable.il_business_yen_circle, "l", "business"),
        Icon(R.drawable.il_chat_chat, "l", "chat"),
        Icon(R.drawable.il_chat_chat_bubble_user, "l", "chat"),
        Icon(R.drawable.il_chat_chat_info, "l", "chat"),
        Icon(R.drawable.il_chat_comment, "l", "chat"),
        Icon(R.drawable.il_chat_comments, "l", "chat"),
        Icon(R.drawable.il_chat_comments_alt, "l", "chat"),
        Icon(R.drawable.il_chat_comment_add, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_block, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_chart_lines, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_check, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_dots, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_download, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_edit, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_exclamation, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_heart, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_image, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_info, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_lines, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_lock, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_medical, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_message, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_notes, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_plus, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_question, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_redo, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_search, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_share, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_shield, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_upload, "l", "chat"),
        Icon(R.drawable.il_chat_comment_alt_verify, "l", "chat"),
        Icon(R.drawable.il_chat_comment_block, "l", "chat"),
        Icon(R.drawable.il_chat_comment_chart_line, "l", "chat"),
        Icon(R.drawable.il_chat_comment_check, "l", "chat"),
        Icon(R.drawable.il_chat_comment_dots, "l", "chat"),
        Icon(R.drawable.il_chat_comment_download, "l", "chat"),
        Icon(R.drawable.il_chat_comment_edit, "l", "chat"),
        Icon(R.drawable.il_chat_comment_exclamation, "l", "chat"),
        Icon(R.drawable.il_chat_comment_heart, "l", "chat"),
        Icon(R.drawable.il_chat_comment_image, "l", "chat"),
        Icon(R.drawable.il_chat_comment_info, "l", "chat"),
        Icon(R.drawable.il_chat_comment_info_alt, "l", "chat"),
        Icon(R.drawable.il_chat_comment_lines, "l", "chat"),
        Icon(R.drawable.il_chat_comment_lock, "l", "chat"),
        Icon(R.drawable.il_chat_comment_medical, "l", "chat"),
        Icon(R.drawable.il_chat_comment_message, "l", "chat"),
        Icon(R.drawable.il_chat_comment_notes, "l", "chat"),
        Icon(R.drawable.il_chat_comment_plus, "l", "chat"),
        Icon(R.drawable.il_chat_comment_question, "l", "chat"),
        Icon(R.drawable.il_chat_comment_redo, "l", "chat"),
        Icon(R.drawable.il_chat_comment_search, "l", "chat"),
        Icon(R.drawable.il_chat_comment_share, "l", "chat"),
        Icon(R.drawable.il_chat_comment_shield, "l", "chat"),
        Icon(R.drawable.il_chat_comment_upload, "l", "chat"),
        Icon(R.drawable.il_chat_comment_verify, "l", "chat"),
        Icon(R.drawable.il_chat_share, "l", "chat"),
        Icon(R.drawable.il_communication_calling, "l", "communication"),
        Icon(
            R.drawable.il_communication_desktop_cloud_alt,
            "l",
            cat = "communication"
        ),
        Icon(R.drawable.il_communication_envelope, "l", "communication"),
        Icon(R.drawable.il_communication_envelopes, "l", "communication"),
        Icon(R.drawable.il_communication_envelope_add, "l", "communication"),
        Icon(R.drawable.il_communication_envelope_alt, "l", "communication"),
        Icon(
            R.drawable.il_communication_envelope_block,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_bookmark,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_check,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_download,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_download_alt,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_edit,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_exclamation,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_heart,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_info,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_lock,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_minus,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_open,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_question,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_receive,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_redo,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_search,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_send,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_share,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_shield,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_star,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_times,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_upload,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_envelope_upload_alt,
            "l",
            cat = "communication"
        ),
        Icon(R.drawable.il_communication_fast_mail, "l", "communication"),
        Icon(
            R.drawable.il_communication_fast_mail_alt,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_forwaded_call,
            "l",
            cat = "communication"
        ),
        Icon(
            R.drawable.il_communication_incoming_call,
            "l",
            cat = "communication"
        ),
        Icon(R.drawable.il_communication_laptop_cloud, "l", "communication"),
        Icon(
            R.drawable.il_communication_laptop_connection,
            "l",
            cat = "communication"
        ),
        Icon(R.drawable.il_communication_mailbox, "l", "communication"),
        Icon(R.drawable.il_communication_mailbox_alt, "l", "communication"),
        Icon(R.drawable.il_communication_missed_call, "l", "communication"),
        Icon(
            R.drawable.il_communication_outgoing_call,
            "l",
            cat = "communication"
        ),
        Icon(R.drawable.il_communication_phone, "l", "communication"),
        Icon(R.drawable.il_communication_phone_alt, "l", "communication"),
        Icon(R.drawable.il_communication_phone_pause, "l", "communication"),
        Icon(R.drawable.il_communication_phone_slash, "l", "communication"),
        Icon(R.drawable.il_communication_phone_times, "l", "communication"),
        Icon(R.drawable.il_communication_phone_volume, "l", "communication"),
        Icon(R.drawable.il_communication_postcard, "l", "communication"),
        Icon(R.drawable.il_communication_post_stamp, "l", "communication"),
        Icon(R.drawable.il_communication_rss_alt, "l", "communication"),
        Icon(R.drawable.il_construction_constructor, "l", "construction"),
        Icon(R.drawable.il_construction_drill, "l", "construction"),
        Icon(R.drawable.il_construction_hard_hat, "l", "construction"),
        Icon(R.drawable.il_construction_jackhammer, "l", "construction"),
        Icon(R.drawable.il_construction_no_entry, "l", "construction"),
        Icon(R.drawable.il_construction_paint_tool, "l", "construction"),
        Icon(R.drawable.il_construction_screw, "l", "construction"),
        Icon(R.drawable.il_construction_shovel, "l", "construction"),
        Icon(R.drawable.il_construction_tape, "l", "construction"),
        Icon(
            R.drawable.il_construction_traffic_barrier,
            "l",
            cat = "construction"
        ),
        Icon(R.drawable.il_construction_trowel, "l", "construction"),
        Icon(R.drawable.il_construction_wall, "l", "construction"),
        Icon(R.drawable.il_construction_wheel_barrow, "l", "construction"),
        Icon(R.drawable.il_content_align, "l", "content"),
        Icon(R.drawable.il_content_align_alt, "l", "content"),
        Icon(R.drawable.il_content_align_center, "l", "content"),
        Icon(R.drawable.il_content_align_center_alt, "l", "content"),
        Icon(R.drawable.il_content_align_center_justify, "l", "content"),
        Icon(R.drawable.il_content_align_justify, "l", "content"),
        Icon(R.drawable.il_content_align_left, "l", "content"),
        Icon(R.drawable.il_content_align_left_justify, "l", "content"),
        Icon(R.drawable.il_content_align_letter_right, "l", "content"),
        Icon(R.drawable.il_content_align_right, "l", "content"),
        Icon(R.drawable.il_content_align_right_justify, "l", "content"),
        Icon(R.drawable.il_content_bars, "l", "content"),
        Icon(R.drawable.il_content_bold, "l", "content"),
        Icon(R.drawable.il_content_border_alt, "l", "content"),
        Icon(R.drawable.il_content_border_bottom, "l", "content"),
        Icon(R.drawable.il_content_border_clear, "l", "content"),
        Icon(R.drawable.il_content_border_horizontal, "l", "content"),
        Icon(R.drawable.il_content_border_inner, "l", "content"),
        Icon(R.drawable.il_content_border_left, "l", "content"),
        Icon(R.drawable.il_content_border_right, "l", "content"),
        Icon(R.drawable.il_content_border_top, "l", "content"),
        Icon(R.drawable.il_content_border_vertical, "l", "content"),
        Icon(R.drawable.il_content_dialpad, "l", "content"),
        Icon(R.drawable.il_content_dialpad_alt, "l", "content"),
        Icon(R.drawable.il_content_document_layout_center, "l", "content"),
        Icon(R.drawable.il_content_document_layout_left, "l", "content"),
        Icon(R.drawable.il_content_document_layout_right, "l", "content"),
        Icon(R.drawable.il_content_english_to_chinese, "l", "content"),
        Icon(R.drawable.il_content_font, "l", "content"),
        Icon(R.drawable.il_content_grip_horizontal_line, "l", "content"),
        Icon(R.drawable.il_content_hindi_to_chinese, "l", "content"),
        Icon(R.drawable.il_content_italic, "l", "content"),
        Icon(R.drawable.il_content_language, "l", "content"),
        Icon(R.drawable.il_content_left_indent, "l", "content"),
        Icon(R.drawable.il_content_left_indent_alt, "l", "content"),
        Icon(
            R.drawable.il_content_left_to_right_text_direction,
            "l",
            cat = "content"
        ),
        Icon(R.drawable.il_content_letter_chinese_a, "l", "content"),
        Icon(R.drawable.il_content_letter_english_a, "l", "content"),
        Icon(R.drawable.il_content_letter_hindi_a, "l", "content"),
        Icon(R.drawable.il_content_letter_japanese_a, "l", "content"),
        Icon(R.drawable.il_content_list_ui_alt, "l", "content"),
        Icon(R.drawable.il_content_list_ul, "l", "content"),
        Icon(R.drawable.il_content_paragraph, "l", "content"),
        Icon(R.drawable.il_content_right_indent_alt, "l", "content"),
        Icon(
            R.drawable.il_content_right_to_left_text_direction,
            "l",
            cat = "content"
        ),
        Icon(R.drawable.il_content_sigma, "l", "content"),
        Icon(R.drawable.il_content_sort_amount_down, "l", "content"),
        Icon(R.drawable.il_content_sort_amount_up, "l", "content"),
        Icon(R.drawable.il_content_subject, "l", "content"),
        Icon(R.drawable.il_content_text, "l", "content"),
        Icon(R.drawable.il_content_text_fields, "l", "content"),
        Icon(R.drawable.il_content_text_size, "l", "content"),
        Icon(R.drawable.il_content_text_strike_through, "l", "content"),
        Icon(R.drawable.il_content_underline, "l", "content"),
        Icon(R.drawable.il_content_wrap_text, "l", "content"),
        Icon(R.drawable.il_design_apps, "l", "design"),
        Icon(R.drawable.il_design_border_out, "l", "design"),
        Icon(R.drawable.il_design_bring_bottom, "l", "design"),
        Icon(R.drawable.il_design_bring_front, "l", "design"),
        Icon(R.drawable.il_design_brush_alt, "l", "design"),
        Icon(R.drawable.il_design_circle_layer, "l", "design"),
        Icon(R.drawable.il_design_compress, "l", "design"),
        Icon(R.drawable.il_design_compress_lines, "l", "design"),
        Icon(R.drawable.il_design_compress_v, "l", "design"),
        Icon(R.drawable.il_design_crop_alt, "l", "design"),
        Icon(R.drawable.il_design_crop_alt_rotate_left, "l", "design"),
        Icon(R.drawable.il_design_crop_alt_rotate_right, "l", "design"),
        Icon(R.drawable.il_design_exclude, "l", "design"),
        Icon(R.drawable.il_design_flip_h, "l", "design"),
        Icon(R.drawable.il_design_flip_h_alt, "l", "design"),
        Icon(R.drawable.il_design_flip_v, "l", "design"),
        Icon(R.drawable.il_design_flip_v_alt, "l", "design"),
        Icon(R.drawable.il_design_grids, "l", "design"),
        Icon(R.drawable.il_design_horizontal_align_center, "l", "design"),
        Icon(R.drawable.il_design_horizontal_align_left, "l", "design"),
        Icon(R.drawable.il_design_horizontal_align_right, "l", "design"),
        Icon(
            R.drawable.il_design_horizontal_distribution_center,
            "l",
            cat = "design"
        ),
        Icon(
            R.drawable.il_design_horizontal_distribution_left,
            "l",
            cat = "design"
        ),
        Icon(
            R.drawable.il_design_horizontal_distribution_right,
            "l",
            cat = "design"
        ),
        Icon(R.drawable.il_design_icons, "l", "design"),
        Icon(R.drawable.il_design_illustration, "l", "design"),
        Icon(R.drawable.il_design_image_resize_landscape, "l", "design"),
        Icon(R.drawable.il_design_image_resize_square, "l", "design"),
        Icon(R.drawable.il_design_layers_alt, "l", "design"),
        Icon(R.drawable.il_design_line_alt, "l", "design"),
        Icon(R.drawable.il_design_line_spacing, "l", "design"),
        Icon(R.drawable.il_design_minus_path, "l", "design"),
        Icon(R.drawable.il_design_object_group, "l", "design"),
        Icon(R.drawable.il_design_object_ungroup, "l", "design"),
        Icon(R.drawable.il_design_palette, "l", "design"),
        Icon(R.drawable.il_design_panorama_h, "l", "design"),
        Icon(R.drawable.il_design_panorama_h_alt, "l", "design"),
        Icon(R.drawable.il_design_panorama_v, "l", "design"),
        Icon(R.drawable.il_design_pathfinder, "l", "design"),
        Icon(R.drawable.il_design_pathfinder_unite, "l", "design"),
        Icon(R.drawable.il_design_repeat, "l", "design"),
        Icon(R.drawable.il_design_ruler, "l", "design"),
        Icon(R.drawable.il_design_ruler_combined, "l", "design"),
        Icon(R.drawable.il_design_shrink, "l", "design"),
        Icon(R.drawable.il_design_spin, "l", "design"),
        Icon(R.drawable.il_design_square_full, "l", "design"),
        Icon(R.drawable.il_design_table, "l", "design"),
        Icon(R.drawable.il_design_th, "l", "design"),
        Icon(R.drawable.il_design_th_large, "l", "design"),
        Icon(R.drawable.il_design_th_slash, "l", "design"),
        Icon(R.drawable.il_design_vector_square, "l", "design"),
        Icon(R.drawable.il_design_vector_square_alt, "l", "design"),
        Icon(R.drawable.il_design_vertical_align_bottom, "l", "design"),
        Icon(R.drawable.il_design_vertical_align_center, "l", "design"),
        Icon(R.drawable.il_design_vertical_align_top, "l", "design"),
        Icon(R.drawable.il_design_vertical_distribute_bottom, "l", "design"),
        Icon(
            R.drawable.il_design_vertical_distribution_center,
            "l",
            cat = "design"
        ),
        Icon(R.drawable.il_design_vertical_distribution_top, "l", "design"),
        Icon(R.drawable.il_device_circuit, "l", "device"),
        Icon(R.drawable.il_device_desktop, "l", "device"),
        Icon(R.drawable.il_device_desktop_alt, "l", "device"),
        Icon(R.drawable.il_device_hdd, "l", "device"),
        Icon(R.drawable.il_device_laptop, "l", "device"),
        Icon(R.drawable.il_device_mobile_android, "l", "device"),
        Icon(R.drawable.il_device_mobile_android_alt, "l", "device"),
        Icon(R.drawable.il_device_modem, "l", "device"),
        Icon(R.drawable.il_device_monitor, "l", "device"),
        Icon(R.drawable.il_device_mouse, "l", "device"),
        Icon(R.drawable.il_device_mouse_alt, "l", "device"),
        Icon(R.drawable.il_device_mouse_alt_2, "l", "device"),
        Icon(R.drawable.il_device_print, "l", "device"),
        Icon(R.drawable.il_device_processor, "l", "device"),
        Icon(R.drawable.il_device_tablet, "l", "device"),
        Icon(R.drawable.il_device_webcam, "l", "device"),
        Icon(R.drawable.il_device_weight, "l", "device"),
        Icon(R.drawable.il_device_wifi_router, "l", "device"),
        Icon(R.drawable.il_education_abacus, "l", "education"),
        Icon(R.drawable.il_education_atom, "l", "education"),
        Icon(R.drawable.il_education_award, "l", "education"),
        Icon(R.drawable.il_education_award_alt, "l", "education"),
        Icon(R.drawable.il_education_backpack, "l", "education"),
        Icon(R.drawable.il_education_bell_school, "l", "education"),
        Icon(R.drawable.il_education_book, "l", "education"),
        Icon(R.drawable.il_education_book_alt, "l", "education"),
        Icon(R.drawable.il_education_book_open, "l", "education"),
        Icon(R.drawable.il_education_brain, "l", "education"),
        Icon(R.drawable.il_education_cell, "l", "education"),
        Icon(R.drawable.il_education_diary, "l", "education"),
        Icon(R.drawable.il_education_diary_alt, "l", "education"),
        Icon(R.drawable.il_education_dna, "l", "education"),
        Icon(R.drawable.il_education_flask, "l", "education"),
        Icon(R.drawable.il_education_flask_potion, "l", "education"),
        Icon(R.drawable.il_education_game_structure, "l", "education"),
        Icon(R.drawable.il_education_graduation_cap, "l", "education"),
        Icon(R.drawable.il_education_medal, "l", "education"),
        Icon(R.drawable.il_education_meeting_board, "l", "education"),
        Icon(R.drawable.il_education_notebooks, "l", "education"),
        Icon(R.drawable.il_education_notes, "l", "education"),
        Icon(R.drawable.il_education_podium, "l", "education"),
        Icon(R.drawable.il_education_presentation, "l", "education"),
        Icon(R.drawable.il_education_presentation_check, "l", "education"),
        Icon(R.drawable.il_education_presentation_edit, "l", "education"),
        Icon(
            R.drawable.il_education_presentation_lines_alt,
            "l",
            cat = "education"
        ),
        Icon(R.drawable.il_education_presentation_minus, "l", "education"),
        Icon(R.drawable.il_education_presentation_play, "l", "education"),
        Icon(R.drawable.il_education_presentation_plus, "l", "education"),
        Icon(R.drawable.il_education_presentation_times, "l", "education"),
        Icon(R.drawable.il_education_robot, "l", "education"),
        Icon(R.drawable.il_education_sperms, "l", "education"),
        Icon(R.drawable.il_education_telescope, "l", "education"),
        Icon(R.drawable.il_emoji_angry, "l", "emoji"),
        Icon(R.drawable.il_emoji_annoyed, "l", "emoji"),
        Icon(R.drawable.il_emoji_annoyed_alt, "l", "emoji"),
        Icon(R.drawable.il_emoji_confused, "l", "emoji"),
        Icon(R.drawable.il_emoji_dizzy_meh, "l", "emoji"),
        Icon(R.drawable.il_emoji_emoji, "l", "emoji"),
        Icon(R.drawable.il_emoji_frown, "l", "emoji"),
        Icon(R.drawable.il_emoji_grin, "l", "emoji"),
        Icon(R.drawable.il_emoji_grin_tongue_wink, "l", "emoji"),
        Icon(R.drawable.il_emoji_grin_tongue_wink_alt, "l", "emoji"),
        Icon(R.drawable.il_emoji_kid, "l", "emoji"),
        Icon(R.drawable.il_emoji_laughing, "l", "emoji"),
        Icon(R.drawable.il_emoji_meh, "l", "emoji"),
        Icon(R.drawable.il_emoji_meh_alt, "l", "emoji"),
        Icon(R.drawable.il_emoji_meh_closed_eye, "l", "emoji"),
        Icon(R.drawable.il_emoji_nerd, "l", "emoji"),
        Icon(R.drawable.il_emoji_ninja, "l", "emoji"),
        Icon(R.drawable.il_emoji_sad, "l", "emoji"),
        Icon(R.drawable.il_emoji_sad_cry, "l", "emoji"),
        Icon(R.drawable.il_emoji_sad_crying, "l", "emoji"),
        Icon(R.drawable.il_emoji_sad_dizzy, "l", "emoji"),
        Icon(R.drawable.il_emoji_sad_squint, "l", "emoji"),
        Icon(R.drawable.il_emoji_sick, "l", "emoji"),
        Icon(R.drawable.il_emoji_silence, "l", "emoji"),
        Icon(R.drawable.il_emoji_silent_squint, "l", "emoji"),
        Icon(R.drawable.il_emoji_smile, "l", "emoji"),
        Icon(R.drawable.il_emoji_smile_beam, "l", "emoji"),
        Icon(R.drawable.il_emoji_smile_dizzy, "l", "emoji"),
        Icon(R.drawable.il_emoji_smile_squint_wink, "l", "emoji"),
        Icon(R.drawable.il_emoji_smile_squint_wink_alt, "l", "emoji"),
        Icon(R.drawable.il_emoji_smile_wink, "l", "emoji"),
        Icon(R.drawable.il_emoji_smile_wink_alt, "l", "emoji"),
        Icon(R.drawable.il_emoji_squint, "l", "emoji"),
        Icon(R.drawable.il_emoji_surprise, "l", "emoji"),
        Icon(R.drawable.il_emoji_unamused, "l", "emoji"),
        Icon(R.drawable.il_file_books, "l", "file"),
        Icon(R.drawable.il_file_clipboard, "l", "file"),
        Icon(R.drawable.il_file_clipboard_alt, "l", "file"),
        Icon(R.drawable.il_file_clipboard_blank, "l", "file"),
        Icon(R.drawable.il_file_clipboard_notes, "l", "file"),
        Icon(R.drawable.il_file_copy, "l", "file"),
        Icon(R.drawable.il_file_copy_alt, "l", "file"),
        Icon(R.drawable.il_file_copy_landscape, "l", "file"),
        Icon(R.drawable.il_file_document_info, "l", "file"),
        Icon(R.drawable.il_file_file, "l", "file"),
        Icon(R.drawable.il_file_files_landscapes, "l", "file"),
        Icon(R.drawable.il_file_files_landscapes_alt, "l", "file"),
        Icon(R.drawable.il_file_file_alt, "l", "file"),
        Icon(R.drawable.il_file_file_blank, "l", "file"),
        Icon(R.drawable.il_file_file_block_alt, "l", "file"),
        Icon(R.drawable.il_file_file_bookmark_alt, "l", "file"),
        Icon(R.drawable.il_file_file_check, "l", "file"),
        Icon(R.drawable.il_file_file_check_alt, "l", "file"),
        Icon(R.drawable.il_file_file_contract, "l", "file"),
        Icon(R.drawable.il_file_file_contract_dollar, "l", "file"),
        Icon(R.drawable.il_file_file_copy_alt, "l", "file"),
        Icon(R.drawable.il_file_file_download, "l", "file"),
        Icon(R.drawable.il_file_file_download_alt, "l", "file"),
        Icon(R.drawable.il_file_file_edit_alt, "l", "file"),
        Icon(R.drawable.il_file_file_exclamation, "l", "file"),
        Icon(R.drawable.il_file_file_exclamation_alt, "l", "file"),
        Icon(R.drawable.il_file_file_export, "l", "file"),
        Icon(R.drawable.il_file_file_graph, "l", "file"),
        Icon(R.drawable.il_file_file_heart, "l", "file"),
        Icon(R.drawable.il_file_file_import, "l", "file"),
        Icon(R.drawable.il_file_file_info_alt, "l", "file"),
        Icon(R.drawable.il_file_file_landscape, "l", "file"),
        Icon(R.drawable.il_file_file_landscape_alt, "l", "file"),
        Icon(R.drawable.il_file_file_lock_alt, "l", "file"),
        Icon(R.drawable.il_file_file_medical, "l", "file"),
        Icon(R.drawable.il_file_file_minus, "l", "file"),
        Icon(R.drawable.il_file_file_minus_alt, "l", "file"),
        Icon(R.drawable.il_file_file_network, "l", "file"),
        Icon(R.drawable.il_file_file_plus, "l", "file"),
        Icon(R.drawable.il_file_file_plus_alt, "l", "file"),
        Icon(R.drawable.il_file_file_question, "l", "file"),
        Icon(R.drawable.il_file_file_question_alt, "l", "file"),
        Icon(R.drawable.il_file_file_redo_alt, "l", "file"),
        Icon(R.drawable.il_file_file_search_alt, "l", "file"),
        Icon(R.drawable.il_file_file_share_alt, "l", "file"),
        Icon(R.drawable.il_file_file_shield_alt, "l", "file"),
        Icon(R.drawable.il_file_file_times, "l", "file"),
        Icon(R.drawable.il_file_file_times_alt, "l", "file"),
        Icon(R.drawable.il_file_file_upload, "l", "file"),
        Icon(R.drawable.il_file_file_upload_alt, "l", "file"),
        Icon(R.drawable.il_file_folder, "l", "file"),
        Icon(R.drawable.il_file_folder_check, "l", "file"),
        Icon(R.drawable.il_file_folder_download, "l", "file"),
        Icon(R.drawable.il_file_folder_exclamation, "l", "file"),
        Icon(R.drawable.il_file_folder_heart, "l", "file"),
        Icon(R.drawable.il_file_folder_info, "l", "file"),
        Icon(R.drawable.il_file_folder_lock, "l", "file"),
        Icon(R.drawable.il_file_folder_medical, "l", "file"),
        Icon(R.drawable.il_file_folder_minus, "l", "file"),
        Icon(R.drawable.il_file_folder_network, "l", "file"),
        Icon(R.drawable.il_file_folder_open, "l", "file"),
        Icon(R.drawable.il_file_folder_plus, "l", "file"),
        Icon(R.drawable.il_file_folder_question, "l", "file"),
        Icon(R.drawable.il_file_folder_times, "l", "file"),
        Icon(R.drawable.il_file_folder_upload, "l", "file"),
        Icon(R.drawable.il_interface_0_plus, "l", "interface"),
        Icon(R.drawable.il_interface_10_plus, "l", "interface"),
        Icon(R.drawable.il_interface_12_plus, "l", "interface"),
        Icon(R.drawable.il_interface_13_plus, "l", "interface"),
        Icon(R.drawable.il_interface_16_plus, "l", "interface"),
        Icon(R.drawable.il_interface_17_plus, "l", "interface"),
        Icon(R.drawable.il_interface_18_plus, "l", "interface"),
        Icon(R.drawable.il_interface_21_plus, "l", "interface"),
        Icon(R.drawable.il_interface_3_plus, "l", "interface"),
        Icon(R.drawable.il_interface_6_plus, "l", "interface"),
        Icon(R.drawable.il_interface_adjust, "l", "interface"),
        Icon(R.drawable.il_interface_adjust_alt, "l", "interface"),
        Icon(R.drawable.il_interface_adjust_circle, "l", "interface"),
        Icon(R.drawable.il_interface_adjust_half, "l", "interface"),
        Icon(R.drawable.il_interface_anchor, "l", "interface"),
        Icon(R.drawable.il_interface_android_phone_slash, "l", "interface"),
        Icon(R.drawable.il_interface_ankh, "l", "interface"),
        Icon(R.drawable.il_interface_archive_alt, "l", "interface"),
        Icon(R.drawable.il_interface_archway, "l", "interface"),
        Icon(R.drawable.il_interface_asterisk, "l", "interface"),
        Icon(R.drawable.il_interface_at, "l", "interface"),
        Icon(R.drawable.il_interface_auto_flash, "l", "interface"),
        Icon(R.drawable.il_interface_baby_carriage, "l", "interface"),
        Icon(R.drawable.il_interface_backspace, "l", "interface"),
        Icon(R.drawable.il_interface_bag_slash, "l", "interface"),
        Icon(R.drawable.il_interface_balance_scale, "l", "interface"),
        Icon(R.drawable.il_interface_bath, "l", "interface"),
        Icon(R.drawable.il_interface_battery_bolt, "l", "interface"),
        Icon(R.drawable.il_interface_battery_empty, "l", "interface"),
        Icon(R.drawable.il_interface_bed, "l", "interface"),
        Icon(R.drawable.il_interface_bed_double, "l", "interface"),
        Icon(R.drawable.il_interface_bell, "l", "interface"),
        Icon(R.drawable.il_interface_bell_slash, "l", "interface"),
        Icon(R.drawable.il_interface_bluetooth_b, "l", "interface"),
        Icon(R.drawable.il_interface_bolt, "l", "interface"),
        Icon(R.drawable.il_interface_bolt_alt, "l", "interface"),
        Icon(R.drawable.il_interface_bookmark, "l", "interface"),
        Icon(R.drawable.il_interface_bookmark_full, "l", "interface"),
        Icon(R.drawable.il_interface_box, "l", "interface"),
        Icon(R.drawable.il_interface_brightness, "l", "interface"),
        Icon(R.drawable.il_interface_brightness_empty, "l", "interface"),
        Icon(R.drawable.il_interface_brightness_half, "l", "interface"),
        Icon(R.drawable.il_interface_brightness_low, "l", "interface"),
        Icon(R.drawable.il_interface_brightness_minus, "l", "interface"),
        Icon(R.drawable.il_interface_brightness_plus, "l", "interface"),
        Icon(R.drawable.il_interface_building, "l", "interface"),
        Icon(R.drawable.il_interface_bullseye, "l", "interface"),
        Icon(R.drawable.il_interface_calculator, "l", "interface"),
        Icon(R.drawable.il_interface_calendar_slash, "l", "interface"),
        Icon(R.drawable.il_interface_calender, "l", "interface"),
        Icon(R.drawable.il_interface_camera_slash, "l", "interface"),
        Icon(R.drawable.il_interface_cancel, "l", "interface"),
        Icon(R.drawable.il_interface_car, "l", "interface"),
        Icon(R.drawable.il_interface_card_atm, "l", "interface"),
        Icon(R.drawable.il_interface_car_slash, "l", "interface"),
        Icon(R.drawable.il_interface_check, "l", "interface"),
        Icon(R.drawable.il_interface_check_circle, "l", "interface"),
        Icon(R.drawable.il_interface_check_square, "l", "interface"),
        Icon(R.drawable.il_interface_coffee, "l", "interface"),
        Icon(R.drawable.il_interface_cog, "l", "interface"),
        Icon(R.drawable.il_interface_comment_alt_slash, "l", "interface"),
        Icon(R.drawable.il_interface_comment_slash, "l", "interface"),
        Icon(R.drawable.il_interface_create_dashboard, "l", "interface"),
        Icon(R.drawable.il_interface_crockery, "l", "interface"),
        Icon(R.drawable.il_interface_cube, "l", "interface"),
        Icon(R.drawable.il_interface_dashboard, "l", "interface"),
        Icon(R.drawable.il_interface_desktop_alt_slash, "l", "interface"),
        Icon(R.drawable.il_interface_desktop_slash, "l", "interface"),
        Icon(R.drawable.il_interface_draggabledots, "l", "interface"),
        Icon(R.drawable.il_interface_edit, "l", "interface"),
        Icon(R.drawable.il_interface_edit_alt, "l", "interface"),
        Icon(R.drawable.il_interface_elipsis_double_v_alt, "l", "interface"),
        Icon(R.drawable.il_interface_ellipsis_h, "l", "interface"),
        Icon(R.drawable.il_interface_ellipsis_v, "l", "interface"),
        Icon(R.drawable.il_interface_estate, "l", "interface"),
        Icon(R.drawable.il_interface_exclamation, "l", "interface"),
        Icon(R.drawable.il_interface_exclamation_circle, "l", "interface"),
        Icon(R.drawable.il_interface_exclamation_octagon, "l", "interface"),
        Icon(R.drawable.il_interface_exclamation_triangle, "l", "interface"),
        Icon(R.drawable.il_interface_exit, "l", "interface"),
        Icon(R.drawable.il_interface_external_link_alt, "l", "interface"),
        Icon(R.drawable.il_interface_eye_slash, "l", "interface"),
        Icon(R.drawable.il_interface_favorite, "l", "interface"),
        Icon(R.drawable.il_interface_feedback, "l", "interface"),
        Icon(R.drawable.il_interface_fidget_spinner, "l", "interface"),
        Icon(R.drawable.il_interface_file_lanscape_slash, "l", "interface"),
        Icon(R.drawable.il_interface_file_slash, "l", "interface"),
        Icon(R.drawable.il_interface_filter, "l", "interface"),
        Icon(R.drawable.il_interface_filter_slash, "l", "interface"),
        Icon(R.drawable.il_interface_fire, "l", "interface"),
        Icon(R.drawable.il_interface_folder_slash, "l", "interface"),
        Icon(R.drawable.il_interface_football_american, "l", "interface"),
        Icon(R.drawable.il_interface_glass, "l", "interface"),
        Icon(R.drawable.il_interface_glass_martini, "l", "interface"),
        Icon(R.drawable.il_interface_glass_martini_alt, "l", "interface"),
        Icon(
            R.drawable.il_interface_glass_martini_alt_slash,
            "l",
            cat = "interface"
        ),
        Icon(R.drawable.il_interface_glass_tea, "l", "interface"),
        Icon(R.drawable.il_interface_globe, "l", "interface"),
        Icon(R.drawable.il_interface_heart_break, "l", "interface"),
        Icon(R.drawable.il_interface_history, "l", "interface"),
        Icon(R.drawable.il_interface_history_alt, "l", "interface"),
        Icon(R.drawable.il_interface_home, "l", "interface"),
        Icon(R.drawable.il_interface_home_alt, "l", "interface"),
        Icon(R.drawable.il_interface_hourglass, "l", "interface"),
        Icon(R.drawable.il_interface_image_alt_slash, "l", "interface"),
        Icon(R.drawable.il_interface_image_slash, "l", "interface"),
        Icon(R.drawable.il_interface_inbox, "l", "interface"),
        Icon(R.drawable.il_interface_info, "l", "interface"),
        Icon(R.drawable.il_interface_info_circle, "l", "interface"),
        Icon(R.drawable.il_interface_keyboard, "l", "interface"),
        Icon(R.drawable.il_interface_keyboard_alt, "l", "interface"),
        Icon(R.drawable.il_interface_keyboard_hide, "l", "interface"),
        Icon(R.drawable.il_interface_keyboard_show, "l", "interface"),
        Icon(R.drawable.il_interface_key_skeleton, "l", "interface"),
        Icon(R.drawable.il_interface_key_skeleton_alt, "l", "interface"),
        Icon(R.drawable.il_interface_lamp, "l", "interface"),
        Icon(R.drawable.il_interface_layers, "l", "interface"),
        Icon(R.drawable.il_interface_layers_slash, "l", "interface"),
        Icon(R.drawable.il_interface_layer_group, "l", "interface"),
        Icon(R.drawable.il_interface_layer_group_slash, "l", "interface"),
        Icon(R.drawable.il_interface_life_ring, "l", "interface"),
        Icon(R.drawable.il_interface_link, "l", "interface"),
        Icon(R.drawable.il_interface_link_add, "l", "interface"),
        Icon(R.drawable.il_interface_link_alt, "l", "interface"),
        Icon(R.drawable.il_interface_link_broken, "l", "interface"),
        Icon(R.drawable.il_interface_link_h, "l", "interface"),
        Icon(R.drawable.il_interface_list_ol, "l", "interface"),
        Icon(R.drawable.il_interface_list_ol_alt, "l", "interface"),
        Icon(R.drawable.il_interface_lock_slash, "l", "interface"),
        Icon(R.drawable.il_interface_map_marker_slash, "l", "interface"),
        Icon(R.drawable.il_interface_megaphone, "l", "interface"),
        Icon(R.drawable.il_interface_message, "l", "interface"),
        Icon(R.drawable.il_interface_microphone, "l", "interface"),
        Icon(R.drawable.il_interface_minus, "l", "interface"),
        Icon(R.drawable.il_interface_minus_circle, "l", "interface"),
        Icon(R.drawable.il_interface_minus_square, "l", "interface"),
        Icon(R.drawable.il_interface_minus_square_full, "l", "interface"),
        Icon(R.drawable.il_interface_mobile_vibrate, "l", "interface"),
        Icon(R.drawable.il_interface_money_bill_slash, "l", "interface"),
        Icon(R.drawable.il_interface_multiply, "l", "interface"),
        Icon(R.drawable.il_interface_newspaper, "l", "interface"),
        Icon(R.drawable.il_interface_package, "l", "interface"),
        Icon(R.drawable.il_interface_paperclip, "l", "interface"),
        Icon(R.drawable.il_interface_pen, "l", "interface"),
        Icon(R.drawable.il_interface_pizza_slice, "l", "interface"),
        Icon(R.drawable.il_interface_plane, "l", "interface"),
        Icon(R.drawable.il_interface_plane_arrival, "l", "interface"),
        Icon(R.drawable.il_interface_plane_departure, "l", "interface"),
        Icon(R.drawable.il_interface_plane_fly, "l", "interface"),
        Icon(R.drawable.il_interface_plug, "l", "interface"),
        Icon(R.drawable.il_interface_plus, "l", "interface"),
        Icon(R.drawable.il_interface_plus_circle, "l", "interface"),
        Icon(R.drawable.il_interface_plus_square, "l", "interface"),
        Icon(R.drawable.il_interface_power, "l", "interface"),
        Icon(R.drawable.il_interface_print_slash, "l", "interface"),
        Icon(R.drawable.il_interface_process, "l", "interface"),
        Icon(R.drawable.il_interface_pump, "l", "interface"),
        Icon(R.drawable.il_interface_question, "l", "interface"),
        Icon(R.drawable.il_interface_question_circle, "l", "interface"),
        Icon(R.drawable.il_interface_redo, "l", "interface"),
        Icon(R.drawable.il_interface_refresh, "l", "interface"),
        Icon(R.drawable.il_interface_restaurant, "l", "interface"),
        Icon(R.drawable.il_interface_rocket, "l", "interface"),
        Icon(R.drawable.il_interface_rope_way, "l", "interface"),
        Icon(R.drawable.il_interface_rotate_360, "l", "interface"),
        Icon(R.drawable.il_interface_rss, "l", "interface"),
        Icon(R.drawable.il_interface_save, "l", "interface"),
        Icon(R.drawable.il_interface_search, "l", "interface"),
        Icon(R.drawable.il_interface_search_alt, "l", "interface"),
        Icon(R.drawable.il_interface_search_minus, "l", "interface"),
        Icon(R.drawable.il_interface_search_plus, "l", "interface"),
        Icon(R.drawable.il_interface_setting, "l", "interface"),
        Icon(R.drawable.il_interface_share_alt, "l", "interface"),
        Icon(R.drawable.il_interface_signal, "l", "interface"),
        Icon(R.drawable.il_interface_signal_alt, "l", "interface"),
        Icon(R.drawable.il_interface_signin, "l", "interface"),
        Icon(R.drawable.il_interface_signout, "l", "interface"),
        Icon(R.drawable.il_interface_sign_in_alt, "l", "interface"),
        Icon(R.drawable.il_interface_sign_out_alt, "l", "interface"),
        Icon(R.drawable.il_interface_sim_card, "l", "interface"),
        Icon(R.drawable.il_interface_space_key, "l", "interface"),
        Icon(R.drawable.il_interface_spinner, "l", "interface"),
        Icon(R.drawable.il_interface_spinner_alt, "l", "interface"),
        Icon(R.drawable.il_interface_star_half_alt, "l", "interface"),
        Icon(R.drawable.il_interface_streering, "l", "interface"),
        Icon(R.drawable.il_interface_sun, "l", "interface"),
        Icon(R.drawable.il_interface_swatchbook, "l", "interface"),
        Icon(R.drawable.il_interface_swimmer, "l", "interface"),
        Icon(R.drawable.il_interface_sync, "l", "interface"),
        Icon(R.drawable.il_interface_sync_exclamation, "l", "interface"),
        Icon(R.drawable.il_interface_sync_slash, "l", "interface"),
        Icon(R.drawable.il_interface_tachometer_fast, "l", "interface"),
        Icon(R.drawable.il_interface_tachometer_fast_alt, "l", "interface"),
        Icon(R.drawable.il_interface_tear, "l", "interface"),
        Icon(R.drawable.il_interface_thumbs_down, "l", "interface"),
        Icon(R.drawable.il_interface_thumbs_up, "l", "interface"),
        Icon(R.drawable.il_interface_times, "l", "interface"),
        Icon(R.drawable.il_interface_times_circle, "l", "interface"),
        Icon(R.drawable.il_interface_times_square, "l", "interface"),
        Icon(R.drawable.il_interface_toggle_off, "l", "interface"),
        Icon(R.drawable.il_interface_toggle_on, "l", "interface"),
        Icon(R.drawable.il_interface_traffic_light, "l", "interface"),
        Icon(R.drawable.il_interface_trash, "l", "interface"),
        Icon(R.drawable.il_interface_trash_alt, "l", "interface"),
        Icon(R.drawable.il_interface_trees, "l", "interface"),
        Icon(R.drawable.il_interface_tv_retro, "l", "interface"),
        Icon(R.drawable.il_interface_tv_retro_slash, "l", "interface"),
        Icon(R.drawable.il_interface_umbrella, "l", "interface"),
        Icon(R.drawable.il_interface_upload, "l", "interface"),
        Icon(R.drawable.il_interface_utensils, "l", "interface"),
        Icon(R.drawable.il_interface_utensils_alt, "l", "interface"),
        Icon(R.drawable.il_interface_video_slash, "l", "interface"),
        Icon(R.drawable.il_interface_voicemail, "l", "interface"),
        Icon(R.drawable.il_interface_voicemail_rectangle, "l", "interface"),
        Icon(R.drawable.il_interface_volume, "l", "interface"),
        Icon(R.drawable.il_interface_volume_down, "l", "interface"),
        Icon(R.drawable.il_interface_volume_mute, "l", "interface"),
        Icon(R.drawable.il_interface_volume_off, "l", "interface"),
        Icon(R.drawable.il_interface_volume_up, "l", "interface"),
        Icon(R.drawable.il_interface_wallet, "l", "interface"),
        Icon(R.drawable.il_interface_water_drop_slash, "l", "interface"),
        Icon(R.drawable.il_interface_water_glass, "l", "interface"),
        Icon(R.drawable.il_interface_wifi, "l", "interface"),
        Icon(R.drawable.il_interface_wifi_slash, "l", "interface"),
        Icon(R.drawable.il_interface_wrench, "l", "interface"),
        Icon(R.drawable.il_interface_x, "l", "interface"),
        Icon(R.drawable.il_interface_x_add, "l", "interface"),
        Icon(R.drawable.il_interface_yin_yang, "l", "interface"),
        Icon(R.drawable.il_location_compass, "l", "location"),
        Icon(R.drawable.il_location_directions, "l", "location"),
        Icon(R.drawable.il_location_location_arrow, "l", "location"),
        Icon(R.drawable.il_location_location_arrow_alt, "l", "location"),
        Icon(R.drawable.il_location_location_pin_alt, "l", "location"),
        Icon(R.drawable.il_location_location_point, "l", "location"),
        Icon(R.drawable.il_location_map, "l", "location"),
        Icon(R.drawable.il_location_map_marker, "l", "location"),
        Icon(R.drawable.il_location_map_marker_alt, "l", "location"),
        Icon(R.drawable.il_location_map_marker_edit, "l", "location"),
        Icon(R.drawable.il_location_map_marker_info, "l", "location"),
        Icon(R.drawable.il_location_map_marker_minus, "l", "location"),
        Icon(R.drawable.il_location_map_marker_plus, "l", "location"),
        Icon(R.drawable.il_location_map_marker_question, "l", "location"),
        Icon(R.drawable.il_location_map_marker_shield, "l", "location"),
        Icon(R.drawable.il_location_map_pin, "l", "location"),
        Icon(R.drawable.il_location_map_pin_alt, "l", "location"),
        Icon(R.drawable.il_location_navigator, "l", "location"),
        Icon(R.drawable.il_location_sign_alt, "l", "location"),
        Icon(R.drawable.il_location_sign_left, "l", "location"),
        Icon(R.drawable.il_location_sign_right, "l", "location"),
        Icon(R.drawable.il_logo_500px, "l", "logo"),
        Icon(R.drawable.il_logo_adobe, "l", "logo"),
        Icon(R.drawable.il_logo_adobe_alt, "l", "logo"),
        Icon(R.drawable.il_logo_amazon, "l", "logo"),
        Icon(R.drawable.il_logo_android, "l", "logo"),
        Icon(R.drawable.il_logo_android_alt, "l", "logo"),
        Icon(R.drawable.il_logo_apple, "l", "logo"),
        Icon(R.drawable.il_logo_apple_alt, "l", "logo"),
        Icon(R.drawable.il_logo_behance, "l", "logo"),
        Icon(R.drawable.il_logo_behance_alt, "l", "logo"),
        Icon(R.drawable.il_logo_bing, "l", "logo"),
        Icon(R.drawable.il_logo_bitcoin, "l", "logo"),
        Icon(R.drawable.il_logo_bitcoin_alt, "l", "logo"),
        Icon(R.drawable.il_logo_black_berry, "l", "logo"),
        Icon(R.drawable.il_logo_blogger, "l", "logo"),
        Icon(R.drawable.il_logo_blogger_alt, "l", "logo"),
        Icon(R.drawable.il_logo_css3_simple, "l", "logo"),
        Icon(R.drawable.il_logo_discord, "l", "logo"),
        Icon(R.drawable.il_logo_docker, "l", "logo"),
        Icon(R.drawable.il_logo_dribbble, "l", "logo"),
        Icon(R.drawable.il_logo_dropbox, "l", "logo"),
        Icon(R.drawable.il_logo_facebook, "l", "logo"),
        Icon(R.drawable.il_logo_facebook_f, "l", "logo"),
        Icon(R.drawable.il_logo_facebook_messenger, "l", "logo"),
        Icon(R.drawable.il_logo_facebook_messenger_alt, "l", "logo"),
        Icon(R.drawable.il_logo_github, "l", "logo"),
        Icon(R.drawable.il_logo_github_alt, "l", "logo"),
        Icon(R.drawable.il_logo_gitlab, "l", "logo"),
        Icon(R.drawable.il_logo_google, "l", "logo"),
        Icon(R.drawable.il_logo_google_drive, "l", "logo"),
        Icon(R.drawable.il_logo_google_drive_alt, "l", "logo"),
        Icon(R.drawable.il_logo_google_hangouts, "l", "logo"),
        Icon(R.drawable.il_logo_google_hangouts_alt, "l", "logo"),
        Icon(R.drawable.il_logo_google_play, "l", "logo"),
        Icon(R.drawable.il_logo_hipchat, "l", "logo"),
        Icon(R.drawable.il_logo_html3, "l", "logo"),
        Icon(R.drawable.il_logo_html3_alt, "l", "logo"),
        Icon(R.drawable.il_logo_html5, "l", "logo"),
        Icon(R.drawable.il_logo_html5_alt, "l", "logo"),
        Icon(R.drawable.il_logo_instagram, "l", "logo"),
        Icon(R.drawable.il_logo_instagram_alt, "l", "logo"),
        Icon(R.drawable.il_logo_intercom, "l", "logo"),
        Icon(R.drawable.il_logo_intercom_alt, "l", "logo"),
        Icon(R.drawable.il_logo_java_script, "l", "logo"),
        Icon(R.drawable.il_logo_line, "l", "logo"),
        Icon(R.drawable.il_logo_linkedin, "l", "logo"),
        Icon(R.drawable.il_logo_linkedin_alt, "l", "logo"),
        Icon(R.drawable.il_logo_linux, "l", "logo"),
        Icon(R.drawable.il_logo_lottiefiles, "l", "logo"),
        Icon(R.drawable.il_logo_lottiefiles_alt, "l", "logo"),
        Icon(R.drawable.il_logo_master_card, "l", "logo"),
        Icon(R.drawable.il_logo_medium_m, "l", "logo"),
        Icon(R.drawable.il_logo_microsoft, "l", "logo"),
        Icon(R.drawable.il_logo_okta, "l", "logo"),
        Icon(R.drawable.il_logo_opera, "l", "logo"),
        Icon(R.drawable.il_logo_opera_alt, "l", "logo"),
        Icon(R.drawable.il_logo_pagelines, "l", "logo"),
        Icon(R.drawable.il_logo_pagerduty, "l", "logo"),
        Icon(R.drawable.il_logo_paypal, "l", "logo"),
        Icon(R.drawable.il_logo_programming_language, "l", "logo"),
        Icon(R.drawable.il_logo_react, "l", "logo"),
        Icon(R.drawable.il_logo_reddit_alien_alt, "l", "logo"),
        Icon(R.drawable.il_logo_skype, "l", "logo"),
        Icon(R.drawable.il_logo_skype_alt, "l", "logo"),
        Icon(R.drawable.il_logo_slack, "l", "logo"),
        Icon(R.drawable.il_logo_slack_alt, "l", "logo"),
        Icon(R.drawable.il_logo_snapchat_alt, "l", "logo"),
        Icon(R.drawable.il_logo_snapchat_ghost, "l", "logo"),
        Icon(R.drawable.il_logo_snapchat_square, "l", "logo"),
        Icon(R.drawable.il_logo_swiggy, "l", "logo"),
        Icon(R.drawable.il_logo_telegram, "l", "logo"),
        Icon(R.drawable.il_logo_telegram_alt, "l", "logo"),
        Icon(R.drawable.il_logo_tumblr, "l", "logo"),
        Icon(R.drawable.il_logo_tumblr_alt, "l", "logo"),
        Icon(R.drawable.il_logo_tumblr_square, "l", "logo"),
        Icon(R.drawable.il_logo_twitter, "l", "logo"),
        Icon(R.drawable.il_logo_twitter_alt, "l", "logo"),
        Icon(R.drawable.il_logo_visual_studio, "l", "logo"),
        Icon(R.drawable.il_logo_vk, "l", "logo"),
        Icon(R.drawable.il_logo_vk_alt, "l", "logo"),
        Icon(R.drawable.il_logo_vuejs, "l", "logo"),
        Icon(R.drawable.il_logo_vuejs_alt, "l", "logo"),
        Icon(R.drawable.il_logo_whatsapp, "l", "logo"),
        Icon(R.drawable.il_logo_whatsapp_alt, "l", "logo"),
        Icon(R.drawable.il_logo_windows, "l", "logo"),
        Icon(R.drawable.il_logo_wordpress, "l", "logo"),
        Icon(R.drawable.il_logo_wordpress_simple, "l", "logo"),
        Icon(R.drawable.il_logo_youtube, "l", "logo"),
        Icon(R.drawable.il_medical_ambulance, "l", "medical"),
        Icon(
            R.drawable.il_medical_assistive_listening_systems,
            "l",
            cat = "medical"
        ),
        Icon(R.drawable.il_medical_band_aid, "l", "medical"),
        Icon(R.drawable.il_medical_book_medical, "l", "medical"),
        Icon(R.drawable.il_medical_capsule, "l", "medical"),
        Icon(R.drawable.il_medical_clinic_medical, "l", "medical"),
        Icon(R.drawable.il_medical_coronavirus, "l", "medical"),
        Icon(R.drawable.il_medical_ear, "l", "medical"),
        Icon(R.drawable.il_medical_file_medical_alt, "l", "medical"),
        Icon(R.drawable.il_medical_head_side, "l", "medical"),
        Icon(R.drawable.il_medical_head_side_cough, "l", "medical"),
        Icon(R.drawable.il_medical_head_side_mask, "l", "medical"),
        Icon(R.drawable.il_medical_heartbeat, "l", "medical"),
        Icon(R.drawable.il_medical_heart_medical, "l", "medical"),
        Icon(R.drawable.il_medical_heart_rate, "l", "medical"),
        Icon(R.drawable.il_medical_hospital, "l", "medical"),
        Icon(R.drawable.il_medical_hospital_square_sign, "l", "medical"),
        Icon(R.drawable.il_medical_hospital_symbol, "l", "medical"),
        Icon(R.drawable.il_medical_house_user, "l", "medical"),
        Icon(R.drawable.il_medical_medical_drip, "l", "medical"),
        Icon(R.drawable.il_medical_medical_square, "l", "medical"),
        Icon(R.drawable.il_medical_medical_square_full, "l", "medical"),
        Icon(R.drawable.il_medical_medkit, "l", "medical"),
        Icon(R.drawable.il_medical_microscope, "l", "medical"),
        Icon(R.drawable.il_medical_monitor_heart_rate, "l", "medical"),
        Icon(R.drawable.il_medical_prescription_bottle, "l", "medical"),
        Icon(R.drawable.il_medical_sanitizer, "l", "medical"),
        Icon(R.drawable.il_medical_sanitizer_alt, "l", "medical"),
        Icon(R.drawable.il_medical_shield_plus, "l", "medical"),
        Icon(R.drawable.il_medical_social_distancing, "l", "medical"),
        Icon(R.drawable.il_medical_stethoscope, "l", "medical"),
        Icon(R.drawable.il_medical_stethoscope_alt, "l", "medical"),
        Icon(R.drawable.il_medical_store_slash, "l", "medical"),
        Icon(R.drawable.il_medical_stretcher, "l", "medical"),
        Icon(R.drawable.il_medical_syringe, "l", "medical"),
        Icon(R.drawable.il_medical_tablets, "l", "medical"),
        Icon(R.drawable.il_medical_thermometer, "l", "medical"),
        Icon(R.drawable.il_medical_toilet_paper, "l", "medical"),
        Icon(R.drawable.il_medical_user_arrows, "l", "medical"),
        Icon(R.drawable.il_medical_user_md, "l", "medical"),
        Icon(R.drawable.il_medical_user_nurse, "l", "medical"),
        Icon(R.drawable.il_medical_virus_slash, "l", "medical"),
        Icon(R.drawable.il_medical_wheelchair_alt, "l", "medical"),
        Icon(R.drawable.il_multimedia_airplay, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_backward, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_bolt_slash, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_boombox, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_camera, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_camera_change, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_camera_plus, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_clapper_board, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_compact_disc, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_equal_circle, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_film, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_flower, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_forward, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_headphones, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_headphones_alt, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_headphone_slash, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_images, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_block, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_broken, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_check, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_download, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_edit, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_lock, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_minus, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_plus, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_question, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_redo, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_search, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_share, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_shield, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_times, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_upload, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_image_v, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_microphone_slash, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_mountains, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_music, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_music_note, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_music_tune_slash, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_pause, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_pause_circle, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_picture, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_play, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_play_circle, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_previous, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_record_audio, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_rss_interface, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_scenery, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_selfie, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_shutter, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_shutter_alt, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_skip_forward, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_skip_forward_alt, "l", "multimedia"),
        Icon(
            R.drawable.il_multimedia_skip_forward_circle,
            "l",
            cat = "multimedia"
        ),
        Icon(R.drawable.il_multimedia_sliders_v, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_sliders_v_alt, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_slider_h, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_slider_h_range, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_step_backward, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_step_backward_alt, "l", "multimedia"),
        Icon(
            R.drawable.il_multimedia_step_backward_circle,
            "l",
            cat = "multimedia"
        ),
        Icon(R.drawable.il_multimedia_step_forward, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_stop_circle, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_ticket, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_video, "l", "multimedia"),
        Icon(R.drawable.il_multimedia_video_question, "l", "multimedia"),
        Icon(R.drawable.il_photography_bright, "l", "photography"),
        Icon(R.drawable.il_photography_capture, "l", "photography"),
        Icon(R.drawable.il_photography_exposure_alt, "l", "photography"),
        Icon(
            R.drawable.il_photography_exposure_increase,
            "l",
            cat = "photography"
        ),
        Icon(R.drawable.il_photography_eye, "l", "photography"),
        Icon(R.drawable.il_photography_focus, "l", "photography"),
        Icon(R.drawable.il_photography_focus_add, "l", "photography"),
        Icon(R.drawable.il_photography_focus_target, "l", "photography"),
        Icon(R.drawable.il_security_keyhole_circle, "l", "security"),
        Icon(R.drawable.il_security_keyhole_square, "l", "security"),
        Icon(R.drawable.il_security_keyhole_square_full, "l", "security"),
        Icon(R.drawable.il_security_lock, "l", "security"),
        Icon(R.drawable.il_security_lock_access, "l", "security"),
        Icon(R.drawable.il_security_lock_alt, "l", "security"),
        Icon(R.drawable.il_security_lock_open_alt, "l", "security"),
        Icon(R.drawable.il_security_padlock, "l", "security"),
        Icon(R.drawable.il_security_shield, "l", "security"),
        Icon(R.drawable.il_security_shield_check, "l", "security"),
        Icon(R.drawable.il_security_shield_exclamation, "l", "security"),
        Icon(R.drawable.il_security_shield_question, "l", "security"),
        Icon(R.drawable.il_security_shield_slash, "l", "security"),
        Icon(R.drawable.il_security_unlock, "l", "security"),
        Icon(R.drawable.il_security_unlock_alt, "l", "security"),
        Icon(R.drawable.il_shape_circle, "l", "shape"),
        Icon(R.drawable.il_shape_heart, "l", "shape"),
        Icon(R.drawable.il_shape_heart_alt, "l", "shape"),
        Icon(R.drawable.il_shape_octagon, "l", "shape"),
        Icon(R.drawable.il_shape_pentagon, "l", "shape"),
        Icon(R.drawable.il_shape_polygon, "l", "shape"),
        Icon(R.drawable.il_shape_square, "l", "shape"),
        Icon(R.drawable.il_shape_square_shape, "l", "shape"),
        Icon(R.drawable.il_shape_star, "l", "shape"),
        Icon(R.drawable.il_shape_triangle, "l", "shape"),
        Icon(R.drawable.il_shopping_archive, "l", "shopping"),
        Icon(R.drawable.il_shopping_credit_card_search, "l", "shopping"),
        Icon(R.drawable.il_shopping_gift, "l", "shopping"),
        Icon(R.drawable.il_shopping_label, "l", "shopping"),
        Icon(R.drawable.il_shopping_label_alt, "l", "shopping"),
        Icon(R.drawable.il_shopping_pricetag_alt, "l", "shopping"),
        Icon(R.drawable.il_shopping_qrcode_scan, "l", "shopping"),
        Icon(R.drawable.il_shopping_shop, "l", "shopping"),
        Icon(R.drawable.il_shopping_shopping_bag, "l", "shopping"),
        Icon(R.drawable.il_shopping_shopping_basket, "l", "shopping"),
        Icon(R.drawable.il_shopping_shopping_cart, "l", "shopping"),
        Icon(R.drawable.il_shopping_shopping_cart_alt, "l", "shopping"),
        Icon(R.drawable.il_shopping_store, "l", "shopping"),
        Icon(R.drawable.il_shopping_store_alt, "l", "shopping"),
        Icon(R.drawable.il_shopping_tag, "l", "shopping"),
        Icon(R.drawable.il_shopping_tag_alt, "l", "shopping"),
        Icon(R.drawable.il_shopping_transaction, "l", "shopping"),
        Icon(R.drawable.il_sport_baseball_ball, "l", "sport"),
        Icon(R.drawable.il_sport_basketball, "l", "sport"),
        Icon(R.drawable.il_sport_basketball_hoop, "l", "sport"),
        Icon(R.drawable.il_sport_bowling_ball, "l", "sport"),
        Icon(R.drawable.il_sport_club, "l", "sport"),
        Icon(R.drawable.il_sport_diamond, "l", "sport"),
        Icon(R.drawable.il_sport_dice_five, "l", "sport"),
        Icon(R.drawable.il_sport_dice_four, "l", "sport"),
        Icon(R.drawable.il_sport_dice_one, "l", "sport"),
        Icon(R.drawable.il_sport_dice_six, "l", "sport"),
        Icon(R.drawable.il_sport_dice_three, "l", "sport"),
        Icon(R.drawable.il_sport_dice_two, "l", "sport"),
        Icon(R.drawable.il_sport_dumbbell, "l", "sport"),
        Icon(R.drawable.il_sport_football, "l", "sport"),
        Icon(R.drawable.il_sport_football_ball, "l", "sport"),
        Icon(R.drawable.il_sport_golf_ball, "l", "sport"),
        Icon(R.drawable.il_sport_heart_sign, "l", "sport"),
        Icon(R.drawable.il_sport_kayak, "l", "sport"),
        Icon(R.drawable.il_sport_spade, "l", "sport"),
        Icon(R.drawable.il_sport_table_tennis, "l", "sport"),
        Icon(R.drawable.il_sport_tennis_ball, "l", "sport"),
        Icon(R.drawable.il_sport_trophy, "l", "sport"),
        Icon(R.drawable.il_sport_volleyball, "l", "sport"),
        Icon(R.drawable.il_symbol_accessible_icon_alt, "l", "symbol"),
        Icon(R.drawable.il_symbol_ban, "l", "symbol"),
        Icon(R.drawable.il_symbol_closed_captioning, "l", "symbol"),
        Icon(R.drawable.il_symbol_closed_captioning_slash, "l", "symbol"),
        Icon(R.drawable.il_symbol_copyright, "l", "symbol"),
        Icon(R.drawable.il_symbol_creative_commons_pd, "l", "symbol"),
        Icon(R.drawable.il_symbol_mars, "l", "symbol"),
        Icon(R.drawable.il_symbol_parking_circle, "l", "symbol"),
        Icon(R.drawable.il_symbol_parking_square, "l", "symbol"),
        Icon(R.drawable.il_symbol_registered, "l", "symbol"),
        Icon(R.drawable.il_symbol_servicemark, "l", "symbol"),
        Icon(R.drawable.il_symbol_trademark, "l", "symbol"),
        Icon(R.drawable.il_symbol_trademark_circle, "l", "symbol"),
        Icon(R.drawable.il_symbol_venus, "l", "symbol"),
        Icon(R.drawable.il_symbol_wheelchair, "l", "symbol"),
        Icon(R.drawable.il_time_clock, "l", "time"),
        Icon(R.drawable.il_time_clock_eight, "l", "time"),
        Icon(R.drawable.il_time_clock_five, "l", "time"),
        Icon(R.drawable.il_time_clock_nine, "l", "time"),
        Icon(R.drawable.il_time_clock_seven, "l", "time"),
        Icon(R.drawable.il_time_clock_ten, "l", "time"),
        Icon(R.drawable.il_time_clock_three, "l", "time"),
        Icon(R.drawable.il_time_clock_two, "l", "time"),
        Icon(R.drawable.il_time_stopwatch, "l", "time"),
        Icon(R.drawable.il_time_stopwatch_slash, "l", "time"),
        Icon(R.drawable.il_time_watch, "l", "time"),
        Icon(R.drawable.il_time_watch_alt, "l", "time"),
        Icon(R.drawable.il_transport_bus, "l", "transport"),
        Icon(R.drawable.il_transport_bus_alt, "l", "transport"),
        Icon(R.drawable.il_transport_bus_school, "l", "transport"),
        Icon(R.drawable.il_transport_car_sideview, "l", "transport"),
        Icon(R.drawable.il_transport_car_wash, "l", "transport"),
        Icon(R.drawable.il_transport_luggage_cart, "l", "transport"),
        Icon(R.drawable.il_transport_metro, "l", "transport"),
        Icon(R.drawable.il_transport_parcel, "l", "transport"),
        Icon(R.drawable.il_transport_ship, "l", "transport"),
        Icon(R.drawable.il_transport_subway, "l", "transport"),
        Icon(R.drawable.il_transport_subway_alt, "l", "transport"),
        Icon(R.drawable.il_transport_taxi, "l", "transport"),
        Icon(R.drawable.il_transport_truck, "l", "transport"),
        Icon(R.drawable.il_transport_truck_loading, "l", "transport"),
        Icon(R.drawable.il_user_book_reader, "l", "user"),
        Icon(R.drawable.il_user_user, "l", "user"),
        Icon(R.drawable.il_user_users_alt, "l", "user"),
        Icon(R.drawable.il_user_user_check, "l", "user"),
        Icon(R.drawable.il_user_user_circle, "l", "user"),
        Icon(R.drawable.il_user_user_exclamation, "l", "user"),
        Icon(R.drawable.il_user_user_location, "l", "user"),
        Icon(R.drawable.il_user_user_minus, "l", "user"),
        Icon(R.drawable.il_user_user_plus, "l", "user"),
        Icon(R.drawable.il_user_user_square, "l", "user"),
        Icon(R.drawable.il_user_user_times, "l", "user"),
        Icon(R.drawable.il_weather_celsius, "l", "weather"),
        Icon(R.drawable.il_weather_cloud, "l", "weather"),
        Icon(R.drawable.il_weather_clouds, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_drizzle, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_hail, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_meatball, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_moon, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_moon_hail, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_moon_meatball, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_moon_rain, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_moon_showers, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_rain, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_rain_sun, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_showers, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_showers_alt, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_showers_heavy, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_sun, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_sun_hail, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_sun_meatball, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_sun_rain, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_sun_rain_alt, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_sun_tear, "l", "weather"),
        Icon(R.drawable.il_weather_cloud_wind, "l", "weather"),
        Icon(R.drawable.il_weather_desert, "l", "weather"),
        Icon(R.drawable.il_weather_fahrenheit, "l", "weather"),
        Icon(R.drawable.il_weather_forecastcloud_moon_tear, "l", "weather"),
        Icon(R.drawable.il_weather_moon, "l", "weather"),
        Icon(R.drawable.il_weather_moonset, "l", "weather"),
        Icon(R.drawable.il_weather_moon_eclipse, "l", "weather"),
        Icon(R.drawable.il_weather_mountains_sun, "l", "weather"),
        Icon(R.drawable.il_weather_n_a, "l", "weather"),
        Icon(R.drawable.il_weather_rainbow, "l", "weather"),
        Icon(R.drawable.il_weather_raindrops, "l", "weather"),
        Icon(R.drawable.il_weather_raindrops_alt, "l", "weather"),
        Icon(R.drawable.il_weather_snowflake, "l", "weather"),
        Icon(R.drawable.il_weather_snowflake_alt, "l", "weather"),
        Icon(R.drawable.il_weather_snow_flake, "l", "weather"),
        Icon(R.drawable.il_weather_sunset, "l", "weather"),
        Icon(R.drawable.il_weather_temperature, "l", "weather"),
        Icon(R.drawable.il_weather_temperature_empty, "l", "weather"),
        Icon(R.drawable.il_weather_temperature_half, "l", "weather"),
        Icon(R.drawable.il_weather_temperature_minus, "l", "weather"),
        Icon(R.drawable.il_weather_temperature_plus, "l", "weather"),
        Icon(R.drawable.il_weather_temperature_quarter, "l", "weather"),
        Icon(
            R.drawable.il_weather_temperature_three_quarter,
            "l",
            cat = "weather"
        ),
        Icon(R.drawable.il_weather_thunderstorm, "l", "weather"),
        Icon(R.drawable.il_weather_thunderstorm_moon, "l", "weather"),
        Icon(R.drawable.il_weather_thunderstorm_sun, "l", "weather"),
        Icon(R.drawable.il_weather_tornado, "l", "weather"),
        Icon(R.drawable.il_weather_water, "l", "weather"),
        Icon(R.drawable.il_weather_wind, "l", "weather"),
        Icon(R.drawable.il_weather_windsock, "l", "weather"),
        Icon(R.drawable.il_weather_windy, "l", "weather"),
        Icon(R.drawable.il_weather_wind_moon, "l", "weather"),
        Icon(R.drawable.il_weather_wind_sun, "l", "weather"),
        Icon(R.drawable.il_web_brackets_curly, "l", "web"),
        Icon(R.drawable.il_web_browser, "l", "web"),
        Icon(R.drawable.il_web_bug, "l", "web"),
        Icon(R.drawable.il_web_channel, "l", "web"),
        Icon(R.drawable.il_web_channel_add, "l", "web"),
        Icon(R.drawable.il_web_cloud_block, "l", "web"),
        Icon(R.drawable.il_web_cloud_bookmark, "l", "web"),
        Icon(R.drawable.il_web_cloud_check, "l", "web"),
        Icon(R.drawable.il_web_cloud_computing, "l", "web"),
        Icon(R.drawable.il_web_cloud_database_tree, "l", "web"),
        Icon(R.drawable.il_web_cloud_data_connection, "l", "web"),
        Icon(R.drawable.il_web_cloud_download, "l", "web"),
        Icon(R.drawable.il_web_cloud_exclamation, "l", "web"),
        Icon(R.drawable.il_web_cloud_heart, "l", "web"),
        Icon(R.drawable.il_web_cloud_info, "l", "web"),
        Icon(R.drawable.il_web_cloud_lock, "l", "web"),
        Icon(R.drawable.il_web_cloud_question, "l", "web"),
        Icon(R.drawable.il_web_cloud_redo, "l", "web"),
        Icon(R.drawable.il_web_cloud_share, "l", "web"),
        Icon(R.drawable.il_web_cloud_shield, "l", "web"),
        Icon(R.drawable.il_web_cloud_slash, "l", "web"),
        Icon(R.drawable.il_web_cloud_times, "l", "web"),
        Icon(R.drawable.il_web_cloud_unlock, "l", "web"),
        Icon(R.drawable.il_web_cloud_upload, "l", "web"),
        Icon(R.drawable.il_web_cloud_wifi, "l", "web"),
        Icon(R.drawable.il_web_code_branch, "l", "web"),
        Icon(R.drawable.il_web_columns, "l", "web"),
        Icon(R.drawable.il_web_database, "l", "web"),
        Icon(R.drawable.il_web_database_alt, "l", "web"),
        Icon(R.drawable.il_web_data_sharing, "l", "web"),
        Icon(R.drawable.il_web_grid, "l", "web"),
        Icon(R.drawable.il_web_server, "l", "web"),
        Icon(R.drawable.il_web_servers, "l", "web"),
        Icon(R.drawable.il_web_server_alt, "l", "web"),
        Icon(R.drawable.il_web_server_connection, "l", "web"),
        Icon(R.drawable.il_web_server_network, "l", "web"),
        Icon(R.drawable.il_web_server_network_alt, "l", "web"),
        Icon(R.drawable.il_web_web_grid, "l", "web"),
        Icon(R.drawable.il_web_web_grid_alt, "l", "web"),
        Icon(R.drawable.il_web_web_section, "l", "web"),
        Icon(R.drawable.il_web_web_section_alt, "l", "web"),
        Icon(R.drawable.il_web_window, "l", "web"),
        Icon(R.drawable.il_web_window_grid, "l", "web"),
        Icon(R.drawable.il_web_window_maximize, "l", "web"),
        Icon(R.drawable.il_web_window_section, "l", "web")
    )

    val cats = listOf(
        "arrow",
        "business",
        "chat",
        "communication",
        "construction",
        "content",
        "design",
        "device",
        "education",
        "emoji",
        "file",
        "interface",
        "location",
        "logo",
        "medical",
        "multimedia",
        "photography",
        "security",
        "shape",
        "shopping",
        "sport",
        "symbol",
        "time",
        "transport",
        "user",
        "weather",
        "web"
    )
}